x-wp-env: &wp-env
  WORDPRESS_DB_HOST: db
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: supersecret
  WORDPRESS_DEBUG: 1
  WORDPRESS_CONFIG_EXTRA: |
    define( 'SCRIPT_DEBUG', true );

volumes:
  db-data:
  akp-wp-data:
  bhd-wp-data:

services:
  db:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./images/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql:ro
  pma:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: supersecret
    ports:
      - 53388:80
  # akp.ba
  bhd:
    build:
      context: images
      dockerfile: wordpress.Dockerfile
    depends_on:
      - db
    environment:
      <<: *wp-env
      WORDPRESS_DB_NAME: bhidapa
    ports:
      - 58387:80
    volumes:
      - bhd-wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./plugins/e-library:/var/www/html/wp-content/plugins/e-library
      - ./themes/bhd:/var/www/html/wp-content/themes/bhd
  akp:
    build:
      context: images
      dockerfile: wordpress.Dockerfile
    depends_on:
      - db
    environment:
      <<: *wp-env
      WORDPRESS_DB_NAME: akp
    ports:
      - 58386:80
    volumes:
      - akp-wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./plugins/e-library:/var/www/html/wp-content/plugins/e-library
      - ./themes/azp:/var/www/html/wp-content/themes/azp
