volumes:
  db-data:
  akp-data:

services:
  db:
    image: mariadb:11.2
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
  akp:
    depends_on:
      - db
    build: ./wp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - 58386:80
    volumes:
      - akp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/akp:/var/www/html/wp-content/themes/akp
