x-wp-env: &wp-env
  WORDPRESS_DB_HOST: db
  WORDPRESS_DB_USER: root
  WORDPRESS_DB_PASSWORD: supersecret
  WORDPRESS_DEBUG: 1

volumes:
  db-data:
  akp-wp-data:

services:
  db:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./services/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql:ro
  pma:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: supersecret
    ports:
      - 53388:80
  # akp.ba
  akp:
    build:
      context: ./services
      dockerfile: ./services/wordpress.Dockerfile
    depends_on:
      - db
    environment:
      <<: *wp-env
      WORDPRESS_DB_NAME: akp
    ports:
      - 58386:80
    volumes:
      - akp-wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./wp-plugins/e-library:/var/www/html/wp-content/plugins/e-library
      - ./themes/azp:/var/www/html/wp-content/themes/azp
