x-fpm: &fpm
  environment: &fpm-environment
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: supersecret
    WORDPRESS_DEBUG: 1
    INTERNAL_PROXY_PORT: 80
  depends_on:
    - db
  build:
    context: ./wp
    dockerfile: fpm.Dockerfile
  healthcheck:
    # also change the healthcheck in infra/index.ts
    test:
      [
        'CMD-SHELL',
        'SCRIPT_NAME=/healthcheck.php SCRIPT_FILENAME=/opt/healthcheck.php cgi-fcgi -bind -connect localhost:9000 | grep -q "X-Powered-By: PHP" || exit 1',
      ]
x-nginx: &nginx
  build:
    context: ./wp
    dockerfile: nginx.Dockerfile
  healthcheck:
    # also change the healthcheck in infra/index.ts
    test: ['CMD-SHELL', 'curl -f http://localhost:80 || exit 1']

volumes:
  db-data:
  akp-wp-data:

services:
  db:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./wp/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql:ro
  pma:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: supersecret
    ports:
      - 53388:80
  # akp.ba
  akp-fpm:
    <<: *fpm
    environment:
      <<: *fpm-environment
      WORDPRESS_DB_NAME: akp
      INTERNAL_PROXY_HOST: akp-nginx
    volumes:
      - akp-wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/azp:/var/www/html/wp-content/themes/azp
  akp-nginx:
    <<: *nginx
    depends_on:
      - akp-fpm
    environment:
      FASTCGI_PASS: akp-fpm:9000
    ports:
      - 58386:80
    volumes:
      - akp-wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/azp:/var/www/html/wp-content/themes/azp
