volumes:
  db-data:
  bhidapa-data:

services:
  db:
    image: mariadb:11.2
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
  bhidapa:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./frankenwp/Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - 58386:80
    volumes:
      - bhidapa-data:/var/www/html
