volumes:
  db-data:
  akp-data:

services:
  db:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./wp/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 53388:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: supersecret
  akp:
    depends_on:
      - db
    build: ./wp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: akp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DEBUG: 1
    ports:
      - 58386:80
    volumes:
      - akp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/azp:/var/www/html/wp-content/themes/azp
