volumes:
  db-data:
  wp-data:

services:
  db:
    image: mariadb:11.8
    environment:
      MARIADB_ROOT_PASSWORD: supersecret
    ports:
      - 53386:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./wp/create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql:ro
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: supersecret
    ports:
      - 53388:80
  fpm:
    depends_on:
      - db
    build:
      context: ./wp
      dockerfile: fpm.Dockerfile
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: supersecret
      WORDPRESS_DEBUG: 1
      INTERNAL_PROXY_HOST: nginx
      INTERNAL_PROXY_PORT: 80
    healthcheck:
      # also change the healthcheck in infra/index.ts
      test:
        [
          'CMD-SHELL',
          'SCRIPT_NAME=/healthcheck.php SCRIPT_FILENAME=/opt/healthcheck.php cgi-fcgi -bind -connect localhost:9000 | grep -q "X-Powered-By: PHP" || exit 1',
        ]
    volumes:
      - wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/azp:/var/www/html/wp-content/themes/azp
  nginx:
    depends_on:
      - fpm
    build:
      context: ./wp
      dockerfile: nginx.Dockerfile
    environment:
      FASTCGI_PASS: fpm:9000
    healthcheck:
      # also change the healthcheck in infra/index.ts
      test: ['CMD-SHELL', 'curl -f http://localhost:80 || exit 1']
    ports:
      - 58386:80
    volumes:
      - wp-data:/var/www/html
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./themes/azp:/var/www/html/wp-content/themes/azp
