name: CD

on:
  push:
    branches:
      - main

# Need ID token write permission to use GitHub OIDC with AWS
permissions:
  id-token: write
  contents: read

jobs:
  checks:
    name: Check ${{ matrix.check }}
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        check:
          - format
          - types
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - run: bun i
      - run: bun check:${{ matrix.check }}

  infra:
    needs: checks
    environment: prod
    name: Infra
    runs-on: ubuntu-24.04-arm # important because the docker image needs to be arm
    concurrency:
      group: infra-prod
      cancel-in-progress: false
    outputs:
      website-names: ${{ steps.infra.outputs.websiteNames }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: oven-sh/setup-bun@v2
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1
      - run: bun i
      - uses: pulumi/actions@v6
        id: infra
        with:
          work-dir: infra
          command: up
          stack-name: ${{ vars.STACK_NAME }}
          suppress-outputs: true

  deploy:
    needs: [checks, infra]
    environment: prod
    name: Deploy ${{ matrix.website }}
    runs-on: ubuntu-24.04-arm
    concurrency:
      group: deploy-prod
      cancel-in-progress: false
    strategy:
      matrix:
        website: ${{ fromJson(needs.infra.outputs.website-names) }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: setup ssh
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_ENDPOINT }} >> ~/.ssh/known_hosts
      - run: bun i
      - run: bun blocks:build
      - env:
          ENDPOINT: 'ec2-user@${{ secrets.SSH_ENDPOINT }}'
          WEBSITE: ${{ matrix.website }}
        run: bun scripts/deploy.ts
