name: Deploy

on:
  push:
    branches:
      - main

# Need ID token write permission to use GitHub OIDC with AWS
permissions:
  id-token: write
  contents: read

jobs:
  infra:
    environment: prod
    name: Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: oven-sh/setup-bun@v2
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1
      - run: bun i
      - uses: pulumi/actions@v6
        id: infra
        with:
          work-dir: infra
          command: up
          stack-name: ${{ vars.STACK_NAME }}

  # TODO: deploy wordpress and migrations
