name: Deploy

on:
  push:
    branches:
      - main

# Need ID token write permission to use GitHub OIDC with AWS
permissions:
  id-token: write
  contents: read

jobs:
  infra:
    environment: prod
    name: Infra
    runs-on: ubuntu-latest
    outputs:
      jump-server-endpoint: ${{ steps.infra.outputs.jumpServerEndpoint }}
      jump-server-username: ${{ steps.infra.outputs.jumpServerUsername }}
      website-names: ${{ steps.infra.outputs.websiteNames }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: oven-sh/setup-bun@v2
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1
      - run: bun i # no cache because bun i is actually faster than storing and restoring actions cache
      - uses: pulumi/actions@v6
        id: infra
        with:
          work-dir: infra
          command: up
          stack-name: ${{ vars.STACK_NAME }}

  deploy:
    needs: infra
    environment: prod
    name: Deploy ${{ matrix.website }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        website: ${{ fromJson(needs.infra.outputs.website-names) }}
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ needs.infra.outputs.jump-server-endpoint }} >> ~/.ssh/known_hosts
      - run: bun i
      - run: bun build
      - env:
          ENDPOINT: '${{ needs.infra.outputs.jump-server-username }}@${{ needs.infra.outputs.jump-server-endpoint }}'
          WEBSITE: ${{ matrix.website }}
        run: bun push
